import { Layout, Layout_File, Layout_Player } from './interfaces';

import fs from 'node:fs';

const F1MV_File = {
    $schema: './layouts.schema.json',
    version: '1',
    layouts: [
        {
            id: 6,
            title: 'Course sur portable',
            windows: [
                {
                    playerData: {
                        volume: 5.769230769230769,
                        muted: false,
                        videoQuality: '1080_10990741',
                        videoQualityBitrate: 6810741,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'INTERNATIONAL',
                        meetingKey: '1125',
                        channelId: 1025,
                        type: 'additional',
                    },
                    bounds: {
                        x: 0,
                        y: 38,
                        width: 1152,
                        height: 648,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '1080_10991011',
                        videoQualityBitrate: 6811011,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'TRACKER',
                        meetingKey: '1125',
                        channelId: 1003,
                        type: 'additional',
                    },
                    bounds: {
                        x: 1152,
                        y: 38,
                        width: 576,
                        height: 324,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '1080_10991153',
                        videoQualityBitrate: 6811153,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'DATA',
                        meetingKey: '1125',
                        channelId: 1004,
                        type: 'additional',
                    },
                    bounds: {
                        x: 1152,
                        y: 362,
                        width: 576,
                        height: 324,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499576',
                        videoQualityBitrate: 4061237,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 10,
                        firstName: 'Pierre',
                        lastName: 'Gasly',
                        teamName: 'AlphaTauri',
                        tla: 'GAS',
                    },
                    streamData: {
                        title: 'GAS',
                        meetingKey: '1125',
                        channelId: 1021,
                        type: 'obc',
                    },
                    bounds: {
                        x: 0,
                        y: 793,
                        width: 576,
                        height: 324,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499696',
                        videoQualityBitrate: 4061357,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 16,
                        firstName: 'Charles',
                        lastName: 'Leclerc',
                        teamName: 'Ferrari',
                        tla: 'LEC',
                    },
                    streamData: {
                        title: 'LEC',
                        meetingKey: '1125',
                        channelId: 1008,
                        type: 'obc',
                    },
                    bounds: {
                        x: 577,
                        y: 793,
                        width: 576,
                        height: 324,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6500191',
                        videoQualityBitrate: 4061852,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 1,
                        firstName: 'Max',
                        lastName: 'Verstappen',
                        teamName: 'Red Bull Racing',
                        tla: 'VER',
                    },
                    streamData: {
                        title: 'VER',
                        meetingKey: '1125',
                        channelId: 1009,
                        type: 'obc',
                    },
                    bounds: {
                        x: 1152,
                        y: 793,
                        width: 576,
                        height: 324,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
            ],
        },
        {
            id: 9,
            title: '[2020] All sources',
            windows: [
                {
                    playerData: {
                        volume: 30.76923076923077,
                        muted: false,
                        audioLanguage: 'fre',
                        videoQuality: '1080_7015190',
                        videoQualityBitrate: 5742536,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'INTERNATIONAL',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 1025,
                        type: 'additional',
                    },
                    bounds: {
                        x: 1402,
                        y: -1440,
                        width: 2560,
                        height: 1440,
                    },
                    isFullScreen: true,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 33,
                        firstName: 'Max',
                        lastName: 'Verstappen',
                        teamName: 'Red Bull Racing',
                        tla: 'VER',
                    },
                    streamData: {
                        title: 'VER',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7442,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2038,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 11,
                        firstName: 'Sergio',
                        lastName: 'Perez',
                        teamName: 'Racing Point',
                        tla: 'PER',
                    },
                    streamData: {
                        title: 'PER',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7450,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1465,
                        y: -318,
                        width: 573,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 16,
                        firstName: 'Charles',
                        lastName: 'Leclerc',
                        teamName: 'Ferrari',
                        tla: 'LEC',
                    },
                    streamData: {
                        title: 'LEC',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7437,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1349,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 55,
                        firstName: 'Carlos',
                        lastName: 'Sainz',
                        teamName: 'McLaren',
                        tla: 'SAI',
                    },
                    streamData: {
                        title: 'SAI',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7434,
                        type: 'obc',
                    },
                    bounds: {
                        x: -321,
                        y: -645,
                        width: 573,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 44,
                        firstName: 'Lewis',
                        lastName: 'Hamilton',
                        teamName: 'Mercedes',
                        tla: 'HAM',
                    },
                    streamData: {
                        title: 'HAM',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7440,
                        type: 'obc',
                    },
                    bounds: {
                        x: 714,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 63,
                        firstName: 'George',
                        lastName: 'Russell',
                        teamName: 'Williams',
                        tla: 'RUS',
                    },
                    streamData: {
                        title: 'RUS',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7438,
                        type: 'obc',
                    },
                    bounds: {
                        x: 253,
                        y: -645,
                        width: 573,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 10,
                        firstName: 'Pierre',
                        lastName: 'Gasly',
                        teamName: 'AlphaTauri',
                        tla: 'GAS',
                    },
                    streamData: {
                        title: 'GAS',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7449,
                        type: 'obc',
                    },
                    bounds: {
                        x: 29,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 31,
                        firstName: 'Esteban',
                        lastName: 'Ocon',
                        teamName: 'Renault',
                        tla: 'OCO',
                    },
                    streamData: {
                        title: 'OCO',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7433,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2038,
                        y: -641,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'TRACKER',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 1003,
                        type: 'additional',
                    },
                    bounds: {
                        x: -660,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'DATA',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 1004,
                        type: 'additional',
                    },
                    bounds: {
                        x: -660,
                        y: -1033,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 18,
                        firstName: 'Lance',
                        lastName: 'Stroll',
                        teamName: 'Racing Point',
                        tla: 'STR',
                    },
                    streamData: {
                        title: 'STR',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7451,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1465,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 20,
                        firstName: 'Kevin',
                        lastName: 'Magnussen',
                        teamName: 'Haas F1 Team',
                        tla: 'MAG',
                    },
                    streamData: {
                        title: 'MAG',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7447,
                        type: 'obc',
                    },
                    bounds: {
                        x: -892,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 3,
                        firstName: 'Daniel',
                        lastName: 'Ricciardo',
                        teamName: 'Renault',
                        tla: 'RIC',
                    },
                    streamData: {
                        title: 'RIC',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7432,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2038,
                        y: -318,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 4,
                        firstName: 'Lando',
                        lastName: 'Norris',
                        teamName: 'McLaren',
                        tla: 'NOR',
                    },
                    streamData: {
                        title: 'NOR',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7435,
                        type: 'obc',
                    },
                    bounds: {
                        x: -318,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 23,
                        firstName: 'Alexander',
                        lastName: 'Albon',
                        teamName: 'Red Bull Racing',
                        tla: 'ALB',
                    },
                    streamData: {
                        title: 'ALB',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7443,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2038,
                        y: -1029,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 6,
                        firstName: 'Nicholas',
                        lastName: 'Latifi',
                        teamName: 'Williams',
                        tla: 'LAT',
                    },
                    streamData: {
                        title: 'LAT',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7439,
                        type: 'obc',
                    },
                    bounds: {
                        x: 254,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 77,
                        firstName: 'Valtteri',
                        lastName: 'Bottas',
                        teamName: 'Mercedes',
                        tla: 'BOT',
                    },
                    streamData: {
                        title: 'BOT',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7441,
                        type: 'obc',
                    },
                    bounds: {
                        x: 713,
                        y: -1033,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_5190321',
                        videoQualityBitrate: 4209836,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 5,
                        firstName: 'Sebastian',
                        lastName: 'Vettel',
                        teamName: 'Ferrari',
                        tla: 'VET',
                    },
                    streamData: {
                        title: 'VET',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7436,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1349,
                        y: -1027,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: 'auto',
                    },
                    driverData: {
                        driverNumber: 99,
                        firstName: 'Antonio',
                        lastName: 'Giovinazzi',
                        teamName: 'Alfa Romeo Racing',
                        tla: 'GIO',
                    },
                    streamData: {
                        title: 'GIO',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7445,
                        type: 'obc',
                    },
                    bounds: {
                        x: 827,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '1080_7015190',
                        videoQualityBitrate: 5742536,
                        videoQualityResolution: [1920, 1080],
                    },
                    driverData: {
                        driverNumber: 7,
                        firstName: 'Kimi',
                        lastName: 'Räikkönen',
                        teamName: 'Alfa Romeo Racing',
                        tla: 'RAI',
                    },
                    streamData: {
                        title: 'RAI',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7444,
                        type: 'obc',
                    },
                    bounds: {
                        x: 829,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: 'auto',
                    },
                    driverData: {
                        driverNumber: 26,
                        firstName: 'Daniil',
                        lastName: 'Kvyat',
                        teamName: 'AlphaTauri',
                        tla: 'KVY',
                    },
                    streamData: {
                        title: 'KVY',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7448,
                        type: 'obc',
                    },
                    bounds: {
                        x: 29,
                        y: -1026,
                        width: 676,
                        height: 380,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: 'auto',
                    },
                    driverData: {
                        driverNumber: 8,
                        firstName: 'Romain',
                        lastName: 'Grosjean',
                        teamName: 'Haas F1 Team',
                        tla: 'GRO',
                    },
                    streamData: {
                        title: 'GRO',
                        meetingKey: '1059',
                        sessionKey: '5918',
                        channelId: 7446,
                        type: 'obc',
                    },
                    bounds: {
                        x: -892,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
            ],
        },
        {
            id: 7,
            title: 'All sources',
            windows: [
                {
                    playerData: {
                        volume: 30.76923076923077,
                        muted: false,
                        videoQuality: '1080_10991373',
                        videoQualityBitrate: 6811373,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'INTERNATIONAL',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1025,
                        type: 'additional',
                    },
                    bounds: {
                        x: 1800,
                        y: -1415,
                        width: 2516,
                        height: 1415,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499627',
                        videoQualityBitrate: 4061288,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 1,
                        firstName: 'Max',
                        lastName: 'Verstappen',
                        teamName: 'Red Bull Racing',
                        tla: 'VER',
                    },
                    streamData: {
                        title: 'VER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1009,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499498',
                        videoQualityBitrate: 4061159,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 11,
                        firstName: 'Sergio',
                        lastName: 'Perez',
                        teamName: 'Red Bull Racing',
                        tla: 'PER',
                    },
                    streamData: {
                        title: 'PER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1011,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -1029,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499741',
                        videoQualityBitrate: 4061402,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 16,
                        firstName: 'Charles',
                        lastName: 'Leclerc',
                        teamName: 'Ferrari',
                        tla: 'LEC',
                    },
                    streamData: {
                        title: 'LEC',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1008,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1875,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499718',
                        videoQualityBitrate: 4061379,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 55,
                        firstName: 'Carlos',
                        lastName: 'Sainz',
                        teamName: 'Ferrari',
                        tla: 'SAI',
                    },
                    streamData: {
                        title: 'SAI',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1007,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1874,
                        y: -1033,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499544',
                        videoQualityBitrate: 4061205,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 44,
                        firstName: 'Lewis',
                        lastName: 'Hamilton',
                        teamName: 'Mercedes',
                        tla: 'HAM',
                    },
                    streamData: {
                        title: 'HAM',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1010,
                        type: 'obc',
                    },
                    bounds: {
                        x: 188,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499563',
                        videoQualityBitrate: 4061224,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 63,
                        firstName: 'George',
                        lastName: 'Russell',
                        teamName: 'Mercedes',
                        tla: 'RUS',
                    },
                    streamData: {
                        title: 'RUS',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1006,
                        type: 'obc',
                    },
                    bounds: {
                        x: 188,
                        y: -1027,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6500479',
                        videoQualityBitrate: 4062140,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 10,
                        firstName: 'Pierre',
                        lastName: 'Gasly',
                        teamName: 'AlphaTauri',
                        tla: 'GAS',
                    },
                    streamData: {
                        title: 'GAS',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1021,
                        type: 'obc',
                    },
                    bounds: {
                        x: -501,
                        y: -1415,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6500035',
                        videoQualityBitrate: 4061696,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 22,
                        firstName: 'Yuki',
                        lastName: 'Tsunoda',
                        teamName: 'AlphaTauri',
                        tla: 'TSU',
                    },
                    streamData: {
                        title: 'TSU',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1022,
                        type: 'obc',
                    },
                    bounds: {
                        x: -501,
                        y: -1027,
                        width: 688,
                        height: 387,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499553',
                        videoQualityBitrate: 4061214,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 31,
                        firstName: 'Esteban',
                        lastName: 'Ocon',
                        teamName: 'Alpine',
                        tla: 'OCO',
                    },
                    streamData: {
                        title: 'OCO',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1012,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -641,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499728',
                        videoQualityBitrate: 4061389,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 14,
                        firstName: 'Fernando',
                        lastName: 'Alonso',
                        teamName: 'Alpine',
                        tla: 'ALO',
                    },
                    streamData: {
                        title: 'ALO',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1005,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499604',
                        videoQualityBitrate: 4061264,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'TRACKER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1003,
                        type: 'additional',
                    },
                    bounds: {
                        x: 877,
                        y: -1415,
                        width: 921,
                        height: 518,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499728',
                        videoQualityBitrate: 4061389,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'DATA',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1004,
                        type: 'additional',
                    },
                    bounds: {
                        x: 877,
                        y: -518,
                        width: 921,
                        height: 518,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499559',
                        videoQualityBitrate: 4061219,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 18,
                        firstName: 'Lance',
                        lastName: 'Stroll',
                        teamName: 'Aston Martin',
                        tla: 'STR',
                    },
                    streamData: {
                        title: 'STR',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1017,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1991,
                        y: -641,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499599',
                        videoQualityBitrate: 4061260,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 20,
                        firstName: 'Kevin',
                        lastName: 'Magnussen',
                        teamName: 'Haas F1 Team',
                        tla: 'MAG',
                    },
                    streamData: {
                        title: 'MAG',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1013,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1418,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499439',
                        videoQualityBitrate: 4061099,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 3,
                        firstName: 'Daniel',
                        lastName: 'Ricciardo',
                        teamName: 'McLaren',
                        tla: 'RIC',
                    },
                    streamData: {
                        title: 'RIC',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1015,
                        type: 'obc',
                    },
                    bounds: {
                        x: -845,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499641',
                        videoQualityBitrate: 4061302,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 4,
                        firstName: 'Lando',
                        lastName: 'Norris',
                        teamName: 'McLaren',
                        tla: 'NOR',
                    },
                    streamData: {
                        title: 'NOR',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1016,
                        type: 'obc',
                    },
                    bounds: {
                        x: -845,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499686',
                        videoQualityBitrate: 4061347,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 23,
                        firstName: 'Alexander',
                        lastName: 'Albon',
                        teamName: 'Williams',
                        tla: 'ALB',
                    },
                    streamData: {
                        title: 'ALB',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1023,
                        type: 'obc',
                    },
                    bounds: {
                        x: -269,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499618',
                        videoQualityBitrate: 4061279,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 6,
                        firstName: 'Nicholas',
                        lastName: 'Latifi',
                        teamName: 'Williams',
                        tla: 'LAT',
                    },
                    streamData: {
                        title: 'LAT',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1024,
                        type: 'obc',
                    },
                    bounds: {
                        x: -269,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499567',
                        videoQualityBitrate: 4061228,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 24,
                        firstName: 'Guanyu',
                        lastName: 'Zhou',
                        teamName: 'Alfa Romeo',
                        tla: 'ZHO',
                    },
                    streamData: {
                        title: 'ZHO',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1020,
                        type: 'obc',
                    },
                    bounds: {
                        x: 304,
                        y: -645,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499595',
                        videoQualityBitrate: 4061256,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 77,
                        firstName: 'Valtteri',
                        lastName: 'Bottas',
                        teamName: 'Alfa Romeo',
                        tla: 'BOT',
                    },
                    streamData: {
                        title: 'BOT',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1019,
                        type: 'obc',
                    },
                    bounds: {
                        x: 304,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499741',
                        videoQualityBitrate: 4061402,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 47,
                        firstName: 'Mick',
                        lastName: 'Schumacher',
                        teamName: 'Haas F1 Team',
                        tla: 'MSC',
                    },
                    streamData: {
                        title: 'MSC',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1014,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1418,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499512',
                        videoQualityBitrate: 4061173,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 5,
                        firstName: 'Sebastian',
                        lastName: 'Vettel',
                        teamName: 'Aston Martin',
                        tla: 'VET',
                    },
                    streamData: {
                        title: 'VET',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1018,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1991,
                        y: -322,
                        width: 572,
                        height: 322,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
            ],
        },
        {
            id: 8,
            title: 'Live',
            windows: [
                {
                    playerData: {
                        volume: 30.76923076923077,
                        muted: false,
                        videoQuality: '1080_10991373',
                        videoQualityBitrate: 6811373,
                        videoQualityResolution: [1920, 1080],
                    },
                    streamData: {
                        title: 'INTERNATIONAL',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1025,
                        type: 'additional',
                    },
                    bounds: {
                        x: 1800,
                        y: -1415,
                        width: 2516,
                        height: 1415,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499627',
                        videoQualityBitrate: 4061288,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 1,
                        firstName: 'Max',
                        lastName: 'Verstappen',
                        teamName: 'Red Bull Racing',
                        tla: 'VER',
                    },
                    streamData: {
                        title: 'VER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1009,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -1415,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499544',
                        videoQualityBitrate: 4061205,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 44,
                        firstName: 'Lewis',
                        lastName: 'Hamilton',
                        teamName: 'Mercedes',
                        tla: 'HAM',
                    },
                    streamData: {
                        title: 'HAM',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1010,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -483,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499563',
                        videoQualityBitrate: 4061224,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 63,
                        firstName: 'George',
                        lastName: 'Russell',
                        teamName: 'Mercedes',
                        tla: 'RUS',
                    },
                    streamData: {
                        title: 'RUS',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1006,
                        type: 'obc',
                    },
                    bounds: {
                        x: 16,
                        y: -483,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499741',
                        videoQualityBitrate: 4061402,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 16,
                        firstName: 'Charles',
                        lastName: 'Leclerc',
                        teamName: 'Ferrari',
                        tla: 'LEC',
                    },
                    streamData: {
                        title: 'LEC',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1008,
                        type: 'obc',
                    },
                    bounds: {
                        x: -2564,
                        y: -945,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499498',
                        videoQualityBitrate: 4061159,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 11,
                        firstName: 'Sergio',
                        lastName: 'Perez',
                        teamName: 'Red Bull Racing',
                        tla: 'PER',
                    },
                    streamData: {
                        title: 'PER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1011,
                        type: 'obc',
                    },
                    bounds: {
                        x: 16,
                        y: -1415,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499718',
                        videoQualityBitrate: 4061379,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 55,
                        firstName: 'Carlos',
                        lastName: 'Sainz',
                        teamName: 'Ferrari',
                        tla: 'SAI',
                    },
                    streamData: {
                        title: 'SAI',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1007,
                        type: 'obc',
                    },
                    bounds: {
                        x: 16,
                        y: -948,
                        width: 859,
                        height: 493,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: false,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6500479',
                        videoQualityBitrate: 4062140,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 10,
                        firstName: 'Pierre',
                        lastName: 'Gasly',
                        teamName: 'AlphaTauri',
                        tla: 'GAS',
                    },
                    streamData: {
                        title: 'GAS',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1021,
                        type: 'obc',
                    },
                    bounds: {
                        x: -1704,
                        y: -483,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499553',
                        videoQualityBitrate: 4061214,
                        videoQualityResolution: [1280, 720],
                    },
                    driverData: {
                        driverNumber: 31,
                        firstName: 'Esteban',
                        lastName: 'Ocon',
                        teamName: 'Alpine',
                        tla: 'OCO',
                    },
                    streamData: {
                        title: 'OCO',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1012,
                        type: 'obc',
                    },
                    bounds: {
                        x: -845,
                        y: -483,
                        width: 859,
                        height: 483,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499604',
                        videoQualityBitrate: 4061264,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'TRACKER',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1003,
                        type: 'additional',
                    },
                    bounds: {
                        x: 877,
                        y: -1415,
                        width: 923,
                        height: 529,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: false,
                },
                {
                    playerData: {
                        volume: 100,
                        muted: true,
                        videoQuality: '720_6499728',
                        videoQualityBitrate: 4061389,
                        videoQualityResolution: [1280, 720],
                    },
                    streamData: {
                        title: 'DATA',
                        meetingKey: '1115',
                        sessionKey: '7197',
                        channelId: 1004,
                        type: 'additional',
                    },
                    bounds: {
                        x: 876,
                        y: -519,
                        width: 923,
                        height: 519,
                    },
                    isFullScreen: false,
                    isAlwaysOnTop: false,
                    maintainAspectRatio: true,
                },
            ],
        },
    ],
};

const { layouts } = F1MV_File;

let final_layout: Layout_File = {
    version: 1,
    // @ts-ignore
    layouts: [],
};

for (let _i = 0; _i < layouts.length; _i++) {
    const layout = layouts[_i];

    const { windows } = layout;

    let this_layout: Layout = {
        id: 0,
        name: '',
        // @ts-ignore
        players: [],
    };

    this_layout.id = layout.id;
    this_layout.name = layout.title;

    for (let _i = 0; _i < windows.length; _i++) {
        const player = windows[_i];
        let this_player: Layout_Player = {
            x: 0,
            y: 0,
            channelId: '',
            width: 0,
        };

        this_player.x = player.bounds.x;
        this_player.y = player.bounds.y;
        this_player.width = player.bounds.width;
        this_player.channelId = player.streamData.channelId.toString();

        this_layout.players.push(this_player);
    }

    final_layout.layouts.push(this_layout);
}

fs.writeFileSync('./layouts.json', JSON.stringify(final_layout));
console.log('Done');
